image: node:14-alpine

stages:
    - test
    - deploy

test:
    stage: test
    script:
        - npm install
        - npm test

# Testing to see if the cache speeds up subsequent builds
cache:
    paths:
        - node_modules/

deploy:
  stage: deploy
  only:
    - master # Deploy only on the master branch
  script:
    # Install dependencies
    - apk --no-cache add curl bash
    - apk add python3=3.7.10-r0 # Install specific version of Python 3.7

    # Download and install Google Cloud SDK
    - curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-353.0.0-linux-x86_64.tar.gz
    - tar zxvf google-cloud-sdk-353.0.0-linux-x86_64.tar.gz
    - ./google-cloud-sdk/install.sh -q
    - source ./google-cloud-sdk/path.bash.inc

    # Deploy
    - echo $GCP_SERVICE_ACCOUNT_KEY > gcp-service-account-key.json
    - gcloud auth activate-service-account --key-file gcp-service-account-key.json
    - gcloud config set project radiant-destiny-392018
    - gcloud builds submit --config cloudbuild.yaml .