image: node:14-alpine

stages:
    - test

before_script:
    - npm install

test:
    stage: test
    script:
        - npm test

# Testing to see if the cache speeds up subsequent builds
cache:
    paths:
        - node_modules/